### ISSUE TITLE
Reporting Incorrect Filesize of Plex library in the rewind breakdown. 

### ISSUE THREAD

**Issue by SiskoUrso** [RaunoT/plex-rewind#109]
### Plex Rewind Version

2.0.0

### Description

Was able to get the new version setup an running, once logged and selected the correct library's in the settings>features. Then going through my rewind it reported that my entire plex library size was 5.25TB which is incorrect by 110TB. 

### Steps to reproduce

1. Spin up docker container.
2. Enter in the requested URL's and API's 
3. Login to plex user
4. Set the features to include the correct library's
5. Run the rewind
6. During the rewind it reports the incorrect size of entire plex library.

### Screenshots

![Screenshot 2024-07-15 215614](https://github.com/user-attachments/assets/287bbee3-19a9-4541-a11d-7aa181354b66)

### Logs

```shell
plex-rewind  |   ▲ Next.js 14.2.5
plex-rewind  |   - Local:        http://localhost:8383
plex-rewind  |   - Network:      http://0.0.0.0:8383
plex-rewind  | 
plex-rewind  |  ✓ Starting...
plex-rewind  |  ✓ Ready in 358ms
plex-rewind  | Settings file not found. Creating a new one.
plex-rewind  | Settings file not found. Creating a new one.
```

### Platform

desktop

### Device

PC

### Operating System

Windows 10

### Browser and version

Firefox 128.0

**Comment by RaunoT** [comment]
The library filesizes are pulled from Tautulli, please verify you have the correct filesize there.
