### ISSUE TITLE
Support for arm64

### ISSUE THREAD

**Issue by phampyk** [RaunoT/plex-rewind#133]
### Description

Hello! I would like to ask if it would be possible to have the docker image to support arm64 too. Back when you had to build it yourself I made it run on the raspberry pi, so I know it's compatible with arm64 too, so it would be a huge help to have the image available for arm64 too. 

Thank you so much, it's a little fun program to have when you share your plex with the family :)

### Desired behavior

To have the docker image compatible with arm64

**Comment by RaunoT** [comment]
Hi @phampyk 👋 I've opened #135 for this. 
Could you please help me test the build for it on your Raspberry Pi?
You can use the SHA for the image tag in docker-compose: `fe09f0cf4f6672c0309ca46083614e417053fb65`

**Comment by phampyk** [comment]
Confirming all working on raspberry pi, only issue that I had was that the images didn't work, but it's because i was using https and the images come from tautulli (I configured the local http) as soon as I put the external https all the images loaded. Probably worth having a note about it on the installation. 

Apart from it everything is working as intended. Thank you so much for it.
