### ISSUE TITLE
Permission denied when creating settings.json

### ISSUE THREAD

**Issue by sincrack** [RaunoT/plex-rewind#144]
### Plex Rewind Version

Latest

### Description

where is the settings file?

### Steps to reproduce

Config docker

### Platform

desktop

### Device

PC

### Operating System

Windows 11

### Browser and version

Chrome latests

**Comment by RaunoT** [comment]
The settings file should be auto-generated upon first launch. 
Please provide log output from `docker ps` and `docker logs <container-id>`

**Comment by PatrickDollard** [comment]
I have the same issue on Unraid.

```
Failed to handle settings file: Error: EACCES: permission denied, open '/app/config/settings.json'
    at async open (node:internal/fs/promises:639:25)
    at async Object.writeFile (node:internal/fs/promises:1219:14)
    at async n (/app/.next/server/chunks/529.js:7:5346)
    at async p (/app/.next/server/app/page.js:1:253255) {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/app/config/settings.json'
}
Error: Unexpected error handling settings file
    at n (/app/.next/server/chunks/529.js:7:5576)
    at async p (/app/.next/server/app/page.js:1:253255) {
  digest: '3340238426'
}
Failed to handle settings file: Error: EACCES: permission denied, open '/app/config/settings.json'
    at async open (node:internal/fs/promises:639:25)
    at async Object.writeFile (node:internal/fs/promises:1219:14)
    at async n (/app/.next/server/chunks/529.js:7:5346)
    at async x (/app/.next/server/chunks/529.js:7:652) {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/app/config/settings.json'
}
Error: Unexpected error handling settings file
    at n (/app/.next/server/chunks/529.js:7:5576)
    at async x (/app/.next/server/chunks/529.js:7:652) {
  digest: '4155864519'
}
Error: Unexpected error handling settings file
    at n (/app/.next/server/chunks/529.js:7:5576)
    at async x (/app/.next/server/chunks/529.js:7:652) {
  digest: '4155864519'
}``
```

I've set the container to privileged with no luck.

**Comment by stukinnear** [comment]
I chmod 777 config/settings.json - made my change, saved then reset to 665.

**Comment by RaunoT** [comment]
I think the issue is that nextjs should be the owner of the file, not nodejs

Please try the following image (make sure you dont already have a settings.json locally) and let me know if it works - `ghcr.io/raunot/plex-rewind:47747b835cd8b6c5490b2c9d235ac344177e95f`

**Comment by nwithan8** [comment]
> I think the issue is that nextjs should be the owner of the file, not nodejs
> 
> Please try the following image (make sure you dont already have a settings.json locally) and let me know if it works - `ghcr.io/raunot/plex-rewind:447747b835cd8b6c5490b2c9d235ac344177e95f`

That new container doesn't fix the issue. The issue is likely on the Unraid side of things, as the "config" path that's getting passed in is using the host system (Unraid) user:group permissions, which is different than the nextjs:nodejs permissions:

<img width="517" alt="image" src="https://github.com/user-attachments/assets/565c6e11-88c8-4c3f-9d58-488ac525a33f">

**Comment by zahidhanif** [comment]
I'm also having the same problem with a non-root docker deployment. My log errors were the same as the OP

**Comment by RaunoT** [comment]
Anyone running into this issue, please try the image based on #162
`ghcr.io/raunot/plex-rewind:2888fc187e387969310d15ead63fbad7fa171f9b`

**Comment by pedroalmaguer** [comment]
Still running in to the same permission error.

**Comment by zahidhanif** [comment]
> I'm also having the same problem with a non-root docker deployment. My log errors were the same as the OP

After removing the config directory and files, I manually created the settings file and it worked. I see there is a new docker image and tested that but getting same permissions issue after clearing everything out.

**Comment by jjscaria** [comment]
> I'm also having the same problem with a non-root docker deployment. My log errors were the same as the OP

same here

**Comment by sideh** [comment]
> > I think the issue is that nextjs should be the owner of the file, not nodejs
> 
> That new container doesn't fix the issue. The issue is likely on the Unraid side of things, as the "config" path that's getting passed in is using the host system (Unraid) user:group permissions, which is different than the nextjs:nodejs permissions:
> 
@nwithan8 Just want to say, the link in in Unraid to the settings.json file doesn't work. Leads to no where.

https://github.com/RaunoT/plex-rewind/blob/develop/config/settings.json

I found one but rather get one that I am directed to. Sorry if this isn't the appropiate place for this information.

**Comment by RaunoT** [comment]
@nwithan8 Regarding Unraid, is there anything we can learn from [Overseerr installation docs](https://docs.overseerr.dev/getting-started/installation#unraid) about this?

Specifically this part about configuring appdata:

> On the following Add Container screen, make changes to the Host Port and Host Path 1(Appdata) as needed.

The general config creation and volume mounting logic is otherwise actually quite similar to Overseerr, as it was something I drew inspiration from during the development of this functionality.

Unfortunately, I don't have too much experience with Docker or different Linux distros. Any input that gets us closer to solving this issue is very welcome!

**Comment by hflatoey** [comment]
> Anyone running into this issue, please try the image based on #162 `ghcr.io/raunot/plex-rewind:2888fc187e387969310d15ead63fbad7fa171f9b`

This worked for me on unRAID.

**Comment by modem7** [comment]
On top of the settings.json issue, I'm also getting:

```

Failed to update prerender cache for 13f6ac5f058c9b663b3f4be14b23e583900e870fe09a3f4e32d7deee1562497c Error: EACCES: permission denied, mkdir '/app/.next/cache'
    at async Object.mkdir (node:internal/fs/promises:858:10)
    at async FileSystemCache.set (/app/node_modules/.pnpm/next@14.2.5_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/incremental-cache/file-system-cache.js:276:13)
    at async IncrementalCache.set (/app/node_modules/.pnpm/next@14.2.5_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/incremental-cache/index.js:411:13)
    at async /app/node_modules/.pnpm/next@14.2.5_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:33864
    at async l (/app/.next/server/app/api/auth/[...nextauth]/route.js:1:5393)
    at async /app/.next/server/app/rewind/page.js:1:46573
    at async Promise.all (index 5)
    at async a (/app/.next/server/app/rewind/page.js:1:46530)
    at async o (/app/.next/server/app/dashboard/[slug]/page.js:1:4760)
    at async Promise.all (index 0) {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/app/.next/cache'
}
```

**Comment by RaunoT** [comment]
@hflatoey and @modem7 thanks for testing, this is of great help.
Could you please try a clean install with `ghcr.io/raunot/plex-rewind:4282e388feabd5245996ea307a35855402451a99` and see if any issues persist? Hopefully this new image will clear up any cache issues also.

**Comment by RaunoT** [comment]
> @hflatoey and @modem7 thanks for testing, this is of great help. Could you please try a clean install with `ghcr.io/raunot/plex-rewind:4282e388feabd5245996ea307a35855402451a99` and see if any issues persist? Hopefully this new image will clear up any cache issues also.

EDIT: the correct image is `ghcr.io/raunot/plex-rewind:7b2d68f7494861956ce3bf008ad6e614eb2b1ea8 `

**Comment by hflatoey** [comment]
I did a clean install and now it created the setting file in unRAID but I gave my url to a few friends of mine and one of them broke it right away by changing the API key in settings...

**Comment by RaunoT** [comment]
> I was wrong, I just checked the log for errors and didn't see any so I though it had created it, none of them creates a setting file for me in unRAID.

The settings file will not be created on install, but rather when visiting the app in the browser for the first time. The app then creates a settings.json if it doesn't exist already on the volume mount. If creation is not successful, you should have an error in the logs, as the app cannot run without it.

**Comment by hflatoey** [comment]
Application error: a server-side exception has occurred (see the server logs for more information).
Digest: 1762202026

`Settings file not found. Creating a new one.
Settings file not found. Creating a new one.
Failed to handle settings file: Error: EACCES: permission denied, open '/app/config/settings.json'
    at async open (node:internal/fs/promises:639:25)
    at async Object.writeFile (node:internal/fs/promises:1219:14)
    at async a (/app/.next/server/app/page.js:8:1799)
    at async p (/app/.next/server/app/page.js:7:1996) {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/app/config/settings.json'
}
Failed to handle settings file: Error: EACCES: permission denied, open '/app/config/settings.json'
    at async open (node:internal/fs/promises:639:25)
    at async Object.writeFile (node:internal/fs/promises:1219:14)
    at async a (/app/.next/server/app/page.js:8:1799)
    at async _ (/app/.next/server/app/page.js:7:650) {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/app/config/settings.json'
}
Error: Unexpected error handling settings file
    at a (/app/.next/server/app/page.js:8:2029)
    at async p (/app/.next/server/app/page.js:7:1996) {
  digest: '606872913'
}
Error: Unexpected error handling settings file
    at a (/app/.next/server/app/page.js:8:2029)
    at async _ (/app/.next/server/app/page.js:7:650) {
  digest: '1762202026'
}
Error: Unexpected error handling settings file
    at a (/app/.next/server/app/page.js:8:2029)
    at async _ (/app/.next/server/app/page.js:7:650) {
  digest: '1762202026'
}
Settings file not found. Creating a new one.
Settings file not found. Creating a new one.
Failed to handle settings file: Error: EACCES: permission denied, open '/app/config/settings.json'
    at async open (node:internal/fs/promises:639:25)
    at async Object.writeFile (node:internal/fs/promises:1219:14)
    at async a (/app/.next/server/app/page.js:8:1799)
    at async p (/app/.next/server/app/page.js:7:1996) {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/app/config/settings.json'
}
Failed to handle settings file: Error: EACCES: permission denied, open '/app/config/settings.json'
    at async open (node:internal/fs/promises:639:25)
    at async Object.writeFile (node:internal/fs/promises:1219:14)
    at async a (/app/.next/server/app/page.js:8:1799)
    at async _ (/app/.next/server/app/page.js:7:650) {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/app/config/settings.json'
}
Error: Unexpected error handling settings file
    at a (/app/.next/server/app/page.js:8:2029)
    at async p (/app/.next/server/app/page.js:7:1996) {
  digest: '606872913'
}
Error: Unexpected error handling settings file
    at a (/app/.next/server/app/page.js:8:2029)
    at async _ (/app/.next/server/app/page.js:7:650) {
  digest: '1762202026'
}
Error: Unexpected error handling settings file
    at a (/app/.next/server/app/page.js:8:2029)
    at async _ (/app/.next/server/app/page.js:7:650) {
  digest: '1762202026'
}
  ▲ Next.js 14.2.5
  - Local:        http://localhost:8383
  - Network:      http://0.0.0.0:8383

 ✓ Starting...
 ✓ Ready in 59ms
  ▲ Next.js 14.2.5
  - Local:        http://localhost:8383
  - Network:      http://0.0.0.0:8383

 ✓ Starting...
 ✓ Ready in 51ms`

**Comment by RaunoT** [comment]
@hflatoey Can you see a config directory being created next to the `docker-compose.yml` after you run `docker compose up`?

**Comment by modem7** [comment]
I haven't had time to test this, but I did come across this:

https://forum.codewithmosh.com/t/docker-npm-permission-denied/4766/6

Specifically the default user alpine uses overrides users.

This may be a red herring, but thought I'd share it just in case. 

Will try to test any requests tonight.

**Comment by hflatoey** [comment]
> @hflatoey Can you see a config directory being created next to the `docker-compose.yml` after you run `docker compose up`?

I don't use docker compose, I used the "app store" in unRAID.

![image](https://github.com/user-attachments/assets/92a88d81-fbce-481c-b512-c3a3a3e90ecf)

**Comment by modem7** [comment]
> > @hflatoey and @modem7 thanks for testing, this is of great help. Could you please try a clean install with `ghcr.io/raunot/plex-rewind:4282e388feabd5245996ea307a35855402451a99` and see if any issues persist? Hopefully this new image will clear up any cache issues also.
> 
> EDIT: the correct image is `ghcr.io/raunot/plex-rewind:7b2d68f7494861956ce3bf008ad6e614eb2b1ea8`

No errors now, however, no images either:

![image](https://github.com/user-attachments/assets/c1caf426-99b8-4f93-847c-5b3cf292b4fd)

**Comment by RaunoT** [comment]
> No errors now, however, no images either:

That's some progress at least I guess :D 
Anything in the browser console regarding images (right click, inspect, console tab)?

**Comment by jjscaria** [comment]
Im still getting the error with the new image on Debian 12 with non-root docker deployment:

```
▲ Next.js 14.2.5
  - Local:        http://localhost:8383/
  - Network:      http://0.0.0.0:8383/

    all values are hidden

 ✓ Starting...
 ✓ Ready in 42ms
Settings file not found. Creating a new one.
Settings file not found. Creating a new one.
Error: Unexpected error handling settings file
    at a (/app/.next/server/app/page.js:8:1831)
    at async p (/app/.next/server/app/page.js:7:1996) {
  digest: '131405523'
}
Error: Unexpected error handling settings file
    at a (/app/.next/server/app/page.js:8:1831)
    at async _ (/app/.next/server/app/page.js:7:650) {
  digest: '1499927976'
}
Error: Unexpected error handling settings file
    at a (/app/.next/server/app/page.js:8:1831)
    at async _ (/app/.next/server/app/page.js:7:650) {
  digest: '1499927976'
}
```

**Comment by nwithan8** [comment]
@RaunoT Sorry I've been absent on this thread. I tried to no avail to figure out what exactly is causing the permission discrepancy and a way to alter them. I do think I found a way around the issue:

The Unraid template has been updated to, instead of mount a folder to `/app/config`, to mount a file at `/app/config/settings.json`. A prerequisite note on the container instructs users will need to download the settings.json file (backed up [here](https://github.com/nwithan8/unraid_templates/blob/main/ref/plex_rewind/settings.json) since you have since deleted it) and place it on their host filesystem BEFORE starting the container. Unfortunately, if the file doesn't exist, Docker will treat the path as a directory mapping rather than a file mapping and will accidentally create an unnecessary folder that users will have to delete.

In initial testing, it seemed that this worked. Anyone who has tried it, please feel free to chime in.

**Comment by RaunoT** [comment]
@nwithan8 No worries and thanks for getting back to me. 

If that's a way we can work around the issues on Unraid, perhaps you could open a PR to update the README and create a `settings-example.json` for it in this repo also 🙏 I added the original settings.json to `.gitignore` to avoid any chance of accidentaly commiting a file with my personal keys while developing.

**Comment by jjscaria** [comment]
> @RaunoT Sorry I've been absent on this thread. I tried to no avail to figure out what exactly is causing the permission discrepancy and a way to alter them. I do think I found a way around the issue:
> 
> The Unraid template has been updated to, instead of mount a folder to `/app/config`, to mount a file at `/app/config/settings.json`. A prerequisite note on the container instructs users will need to download the settings.json file (backed up [here](https://github.com/nwithan8/unraid_templates/blob/main/ref/plex_rewind/settings.json) since you have since deleted it) and place it on their host filesystem BEFORE starting the container. Unfortunately, if the file doesn't exist, Docker will treat the path as a directory mapping rather than a file mapping and will accidentally create an unnecessary folder that users will have to delete.
> 
> In initial testing, it seemed that this worked. Anyone who has tried it, please feel free to chime in.
> 
> I apologize that, in attempts to fix this issue that seemed to be contained to only Unraid Community Apps, that this has now extended to traditional Docker Compose installations (re: #170)

I didnt change the mount point but, copied that settings file and recreated the container and got it working
