### ISSUE TITLE
Removing Audio card for deployments with no Audio

### ISSUE THREAD

**Issue by SnippetSpace** [RaunoT/plex-rewind#176]
### Description

I currently have no Audio libraries only tv/movies. however in my rewind, the last card is "you have not listened to any audio"

### Desired behavior

Hide the audio card by default unless Audio/Music libraries are selected. 

### Additional context

I used to have audio libraries but have removed them, however their data still lives in tautulli. This could explain the behaviour.

**Comment by RaunoT** [comment]
Agreed. I will also tackle adding a generic ending card under this ticket.
