### ISSUE TITLE
Rename dashboard to "Most played"

### ISSUE THREAD

**Issue by SnippetSpace** [RaunoT/plex-rewind#177]
### Description

When logging in and clicking on dashboard, a user would expect to see personal data and statistics. However this is not the case. They just see a list of "top movies" with no context.

### Desired behavior

I would suggest renaming the page to "Most played *movies* on the server" or something similar, to make clear that these are generic statistics

### Additional context

I would also suggest the implementation of a personal dashboard with statistics on most time spent on x TV show for a particular user, and not the entire library

**Comment by RaunoT** [comment]
Thanks for taking the time to submit this, it's a good thought, but I will close this in favor of #178.
