### ISSUE TITLE
Make a personal dashboard

### ISSUE THREAD

**Issue by SnippetSpace** [RaunoT/plex-rewind#178]
### Description

The dashboard today shows generic server data.
The rewind shows generic user data.

There is no way for a user to just see their top 5 tv shows.

### Desired behavior

add a "personal dashboard" with things like top5 TV shows based on time spent watching. Most rewatched movies. Or more creative statistics like:
oldest movie watched
% of requested media watched

etc

**Comment by RaunoT** [comment]
This is a good idea. Thinking of adding a toggle to the dashboard page to toggle between personal/server.
I would rather keep the Dashboard quite general (for now), and leave the creative stuff for Rewind.
