### ISSUE TITLE
Change default period to a drop down

### ISSUE THREAD

**Issue by SnippetSpace** [RaunoT/plex-rewind#179]
### Description

Currently the default period is a free selection that replaces the 2e time value in the dashboard.
It currently behaves as a "custom period" not a "default period"

### Desired behavior

Make it a dropdown for 1 day, 1 week, 1 month, 1 year etc and just select the right view in the dashboard.
right now if I want to set the default to a year view I can't because if I set it to 365 days it just adds a weird 365 value next to the 1 year value.

**Comment by RaunoT** [comment]
This has been released in [2.4.0-develop.3](https://github.com/RaunoT/plex-rewind/releases/tag/v2.4.0-develop.3) and will be part of the next release.
