### ISSUE TITLE
Set order for libraries on dashboard

### ISSUE THREAD

**Issue by SnippetSpace** [RaunoT/plex-rewind#185]
### Description

Currently the order of the tabs for the libraries on the dashboard page are seemily random.
In my case I have 4 libraries that display in this order:
- Anime movies
- Movies
- Anime
- TV shows

Anime movies is my library with the least amount of content and it is the least viewed.

### Desired behavior

options:
1/ Difficult option: add a feature to define the order of the libraries (probably in the same settings section where they are selected).
2/ Easier option: add an option for a "default library" in settings to at least choose which one to open by default.
3/ Interesting option: determine order of libraries based on number of items or number of plays in the library according to Tautulli. For the personal dashboard https://github.com/RaunoT/plex-rewind/issues/178 the order can be based on number of views of a particular library by a particular user.

### Additional context

Thanks for all the other fixes and enhancements in v24 develop 6 so far. IT has transformed the project from good to excellent :)

**Comment by RaunoT** [comment]
Yes, looking to make the libraries re-orderable in the settings section.
