### ISSUE TITLE
Rewind crashes at movies section - s.movies.top[0] is undefined

### ISSUE THREAD

**Issue by silembir** [RaunoT/plex-rewind#205]
### Plex Rewind Version

v3.0.0-develop.5

### Description

Hello,

The Plex Rewind is working for the first 5 or so slides, but suddenly fails with the message "Uh oh.. something went wrong!".  It is the slide directly following the Top 5 TV Shows slide.

Upon looking at the Firefox DevTools, here are the console errors:
```
TypeError: s.movies.top[0] is undefined
    NextJS 28
241-4bdf61aacd7189df.js:1:3969
    NextJS 128
[REWIND] -  TypeError: s.movies.top[0] is undefined
    NextJS 28
241-4bdf61aacd7189df.js:1:3969
    NextJS 129
```

I tried incognito mode as well as other browsers. Here are the relevant console logs from Chrome DevTools:
```
TypeError: Cannot read properties of undefined (reading 'title')
    at G (page-ad1d8e2448c3bc00.js:1:20183)
    at rE (94c12b52-5ae3baf356fa4b3a.js:1:40344)
    at iZ (94c12b52-5ae3baf356fa4b3a.js:1:117029)
    at ia (94c12b52-5ae3baf356fa4b3a.js:1:95165)
    at 94c12b52-5ae3baf356fa4b3a.js:1:94987
    at il (94c12b52-5ae3baf356fa4b3a.js:1:94994)
    at oJ (94c12b52-5ae3baf356fa4b3a.js:1:92350)
    at nb (94c12b52-5ae3baf356fa4b3a.js:1:26836)
    at nw (94c12b52-5ae3baf356fa4b3a.js:1:27574)
    at 94c12b52-5ae3baf356fa4b3a.js:1:28608
```

Any help would be appreciated, thanks!

### Steps to reproduce

1. Start Rewind
2. Click through until it crashes at the 5th slide or so.

### Screenshots

![CleanShot 2024-08-02 at 13 21 13@2x](https://github.com/user-attachments/assets/fb8bceea-88e1-4833-a01b-5f97da9ce44b)

### Platform

desktop

### Device

Macbook Air M2

### Operating System

macOS Sonoma 14.6

### Browser and version

Firefox 128.0.3

**Comment by RaunoT** [comment]
Do you have anything relevant in the server logs for Docker also? 
You can find them with `docker ps` and `docker logs <container-id>`.

**Comment by RaunoT** [comment]
I'm guessing you uncommented the user param because you were getting EACCES errors already before?
Perhaps unrelated to your original issue, but fwiw, I doubt your user:group is 1000:1000. 
You can find out by running `id -u && id -g` in the terminal on mac. The first number will be the user and second the group.

I would also please ask you try the `latest` image instead of `develop` and see if any of the above persists.

**Comment by RaunoT** [comment]
For what it's worth, not setting the user value at all in docker-compose resolves the `EACCES` errors on my macOS machine. But of course, your mileage may vary.

Could you please try the image with tag `9671bbf490d6a0b3f878cfea39884111c2523e7d`, which is based on #207?
I've added additional logging to that image. Please make sure to remove any personal data (mostly the user object) before sharing. But I'm mostly curious what this log looks like for you.

<img width="518" alt="image" src="https://github.com/user-attachments/assets/477552f5-e7a2-4ee9-9167-a2e5219aafda">

In the latest `develop` image, I was checking to see if the `count` object was `> 0`. Probably according to my thinking at the time of writing that code, this would mean that you will have at least have 1 item appear in your `top` object also. 
I've changed the behavior to make sure that the top object actually contains something in `9671bbf490d6a0b3f878cfea39884111c2523e7d` before we show any "Top" Rewind card. Hopefully this alleviates your issue aswell.

**Comment by RaunoT** [comment]
Any updates @silembir?
