### ISSUE TITLE
Dashboard user request count not always shown

### ISSUE THREAD

**Issue by seanecoffey** [RaunoT/plex-rewind#208]
### Plex Rewind Version

v2.5 & v3.0.0-develop.7 

### Description

The request number shown on the user cards on the dashboard are not always shown.
This seems to be for some users and not others.  See screenshot below where all 6 of these users have requests in the last 12 months, but it is only shown for user 3 (which is me, the admin who is logged in).  Under other panels (i.e., 30 days) some other users have their request count shown in the dashboard, but most of the time they do not.
<img width="1392" alt="image" src="https://github.com/user-attachments/assets/0e90a853-ed30-4b2f-8335-266fc5a55dd4">

However, if I view the rewind for the first user in the screenshot above, the request count is determined and shown in the rewind:
<img width="661" alt="image" src="https://github.com/user-attachments/assets/ca70f3b9-0aad-42fd-af7b-c466dff06e1d">

Not sure if related, but I do use display names/nicknames in Tautulli and Overseerr. 
No obvious issues in logs for Plex-Rewind or Overseerr.

### Steps to reproduce

1. Go to dashboard
2. Select "users" tab
3. Compare visible no. of request count next to user compared to what is expected.

### Platform

desktop

### Device

Macbook Pro / Unraid AMD

### Operating System

MacOS Sonoma 14.5 / Docker

### Browser and version

Chrome 127.0.6533.74

**Comment by seanecoffey** [comment]
I've checked this version and can confirm that the issue persists.  With the additional logging I've noticed it isn't fetching the user IDs for the other users:
```
Overseerr is active
Fetching Overseerr data from request?skip=320
Overseerr user ID for Plex user ID true is null
Overseerr user ID for Plex user ID true is null
Overseerr user ID for Plex user ID true is 1
Overseerr user ID for Plex user ID true is null
Overseerr user ID for Plex user ID true is null
Overseerr user ID for Plex user ID true is null
Starting fetchPaginatedOverseerrStats('user/1/requests 2023-08-05T08:47:18.985Z
Fetching Overseerr data from request?skip=330
Fetching Overseerr data from user/1/requests
Fetching Overseerr data from request?skip=340
Fetching Overseerr data from user/1/requests?skip=20
Fetching Overseerr data from request?skip=350
Fetching Overseerr data from user/1/requests?skip=40
Fetching Overseerr data from request?skip=360
```

**Comment by RaunoT** [comment]
> I've checked this version and can confirm that the issue persists. With the additional logging I've noticed it isn't fetching the user IDs for the other users:
> 
> ```
> Overseerr is active
> Fetching Overseerr data from request?skip=320
> Overseerr user ID for Plex user ID true is null
> Overseerr user ID for Plex user ID true is null
> Overseerr user ID for Plex user ID true is 1
> Overseerr user ID for Plex user ID true is null
> Overseerr user ID for Plex user ID true is null
> Overseerr user ID for Plex user ID true is null
> Starting fetchPaginatedOverseerrStats('user/1/requests 2023-08-05T08:47:18.985Z
> Fetching Overseerr data from request?skip=330
> Fetching Overseerr data from user/1/requests
> Fetching Overseerr data from request?skip=340
> Fetching Overseerr data from user/1/requests?skip=20
> Fetching Overseerr data from request?skip=350
> Fetching Overseerr data from user/1/requests?skip=40
> Fetching Overseerr data from request?skip=360
> ```

Are the other users `local` or `plex` users in Overseerr? You can see it under the Users tab in Overseer.

**Comment by seanecoffey** [comment]
Everyone is a "Plex User".
![image](https://github.com/user-attachments/assets/978dc493-dc30-4fad-a64f-4203873563ee)

**Comment by seanecoffey** [comment]
Ah I think I found it.  The  `fetchOverseerrUserId`  function is only searching the first page of users.

I just tested by replacing the function with a paginated search version and it works now:

```tsx
export async function fetchPaginatedOverseerrUserId(
  plexId: string,
): Promise<number | null> {
  const pageSize = 10
  let currentPage = 1
  let totalPages = 1
  let userId: number | null = null

  const fetchUsers = async (
    page: number,
  ): Promise<OverseerrResponse<User[]> | null> => {
    try {
      return await fetchOverseerr<OverseerrResponse<User[]>>(
        `user?skip=${pageSize * (page - 1)}`,
      )
    } catch (error) {
      //Overseerr user not found
      return null
    }
  }

  while (currentPage <= totalPages) {
    const usersResponse = await fetchUsers(currentPage)

    if (usersResponse && usersResponse.results) {
      const user = usersResponse.results.find(
        (user) => String(user.plexId) === plexId,
      )
      if (user) {
        userId = user.id
        break
      }
      totalPages = usersResponse.pageInfo.pages
      currentPage = usersResponse.pageInfo.page + 1
    } else {
      //Overseerr user not found
      break
    }
  }

  return userId
}
```

![image](https://github.com/user-attachments/assets/4e12c6cc-7e7c-4f0e-a66d-49f73d360ee4)

```
Overseerr is active
Overseerr user ID for Plex User ID 1656505 is 1
Overseerr user ID for Plex User ID 14004903 is 16
Overseerr user ID for Plex User ID 6647249 is 20
Overseerr user ID for Plex User ID 3524760 is 11
Overseerr user ID for Plex User ID 113228245 is 21
Overseerr user ID for Plex User ID 14064773 is 24
```

**Comment by RaunoT** [comment]
Brilliant @seanecoffey, thanks for this! I will try to release a fix on develop later today.
