### ISSUE TITLE
Movie availability remains inconsistent

### ISSUE THREAD

**Issue by SnippetSpace** [RaunoT/plex-rewind#215]
### Plex Rewind Version

3.01

### Description

Movies that have been requested through overseerr, are shown as available in overseerr, plex, and tautulli, but remain listed as "request".

The method to query availability seems to not be functioning. Not sure if a bug, and not sure in which software, but perhaps switching the availability query from overseerr to tautulli or vice/versa could help?

### Steps to reproduce

install and configure plex rewind. 
Look at library or rewind tab.

### Screenshots

![image](https://github.com/user-attachments/assets/0ca65cbf-f702-4b44-b1be-19bb36e4e215)
![image](https://github.com/user-attachments/assets/8933f9bb-f697-42c1-9395-0c55f8699f1f)
![image](https://github.com/user-attachments/assets/3a534cbd-708e-4e47-90e3-9c573afa49c9)
![image](https://github.com/user-attachments/assets/4b51ddf2-edf2-40cd-98f8-6d4bbfe3bc0a)

### Platform

desktop

### Device

Windows desktop

### Operating System

Windows 11

### Browser and version

Edge 127

**Comment by SnippetSpace** [comment]
update, I "fixed" this by going into tautulli, to the movie and rematching it to the same IMDB entry.
the rematch has fixed the request banner.

So definitely not a plex rewind issue. however, as this seems to be quite common in my library I assume it will be the same for others. A fallback for a movie/tv show with no "match" would be an improvement.
Double checking availability through the overseerr api might fix this but might also be a bit overkill

**Comment by RaunoT** [comment]
We use Tautulli for the availability status. I think there was a caching issue. Can you please try
`ghcr.io/raunot/plex-rewind:4c596d07d1fa0b8f4c9564903dc16c0e38ad8973` based on #216.

**Comment by SnippetSpace** [comment]
Hello, thanks for the quick fix.

With the above image there is no change.
i.e. the movies that were unavailable remain so.

"Dune: part two" remains unavailable even with the tautullli match "fix"
"Made in Abyss: Dawn of the Deep Soul" remains unavailable because tautulli did not find a match at all, nothing comes up in the "fix match" search.

I assume that if it does not know the  match (tmdb/tvdb?) it returns something else to you even though it can get data including name and poster through plex.

Is there a way to bypass whatever it returns and just use the plex information directly?
It knows there is a file in plex:
![image](https://github.com/user-attachments/assets/a42ad823-993b-4428-9a96-3bbefba0daee)

and if there is a file we can probably assume it is available regardless of the TMDB match entry.

**Comment by RaunoT** [comment]
The core issue here is actually within Plex itself (kinda).
Every time an item gets added into Plex, it is assigned a unique `rating_key`, which is basically just a unique ID.
This same ID is what's used to query data on a media item.

In your case, Dune was added at some time, and given an ID of let's say 1. Then it was deleted and subsequently re-added, given an ID of 2 by Plex. Tautulli reads this ID and does not know it is the same item, therefor it will have 2 separate entities (and play times, etc).

Plex Rewind just reports what Tautulli tells it.

I have run into the same issue on my setup. Manually fixing can work fine for single items and if re-adding doesn't happen too often. Personally I run this script from time-to-time to re-sync re-added items:
https://gist.github.com/JonnyWong16/f554f407832076919dc6864a78432db2 (use at your own risk)

It basically matches the media items by title (and year etc.) to an ID from an external database (imdb, tmdb, tvdb etc.) that is constant. 

So continuing the Dune analogy - Tautulli will show 2 entries Dune (with ID 1) and Dune (with ID 2). That script will go ask an external database (let's say IMDB): "Hey, what's the ID for Dune (2021)". IMDB will say: "It's 3". Then Tautulli will realise that both of the queries for Dune (2021) will return the same IMDB ID of 3, therefore they can be merged into 1 item. I'm not sure why this is not done automatically in Tautulli. Maybe a fear of false positives and messing up the DB. I'm sure they have a good reason.

I'm not sure this is something worth implementing/fixing on Plex Rewind side, as there's a risk of confusion by reporting different data than Tautulli. Considering that's the main source of truth for us, I would rather see some sort of solution at the source.
