### ISSUE TITLE
Version parity

### ISSUE THREAD

**Issue by phampyk** [RaunoT/plex-rewind#245]
### Plex Rewind Version

-

### Description

It's really a very minor issue, but since last version there's a difference in the version announced in GitHub vs the version installed. I just updated my instance and it says it's 4.2.0 while on GitHub is 4.3.0 so it always says it needs to update. 

Last version was the same, Plex rewind said it was 4.1.0 and GitHub was 4.2.0

### Steps to reproduce

-

### Platform

desktop

### Device

-

### Operating System

-

### Browser and version

-

**Comment by RaunoT** [comment]
That's rather interesting, could you please tell me what `/api/status` reports?

**Comment by phampyk** [comment]
> That's rather interesting, could you please tell me what `/api/status` reports?

```{
  "version": "v4.2.0",
  "channel": "stable",
  "updateAvailable": true
}```

**Comment by phampyk** [comment]
![Screenshot_20240907-165206~2](https://github.com/user-attachments/assets/b1e4caaf-25f7-4bcc-969c-ac0c310facc8)
Screenshot from portainer of deployed container

**Comment by RaunoT** [comment]
I'm unable to replicate on `latest`.

The version is set into `NEXT_PUBLIC_VERSION_TAG` env variable at buildtime, so it should produce the same result for everyone, as it's baked into the actual image. The [logs from the build](https://github.com/RaunoT/plex-rewind/actions/runs/10750306418/job/29816295962) confirm this is the case:

```
[9:21:56 AM] [semantic-release] [@semantic-release/exec] › ℹ  Call script echo NEXT_VERSION_TAG=4.3.0 >> $GITHUB_ENV
```

You can check from your image with `docker exec <container-id> printenv NEXT_PUBLIC_VERSION_TAG`
You can get the container id from `docker ps`
The result should be `4.3.0`

Guessing yours will say `4.2.0`, so I suggest you verify you are using `ghcr.io/raunot/plex-rewind:latest` and run 
`docker compose pull && docker compose up -d` once more. 

I'm not sure why your image is reffering to a specific hash in the first place. Not sure of the specifics of your setup, but I would expect it to refer to `ghcr.io/raunot/plex-rewind:latest`. I was unable to find an actual build with the hash in your screenshot.

**Comment by phampyk** [comment]
It is showing now 4.3.0 without me doing anything, I haven't updated or anything since, and I haven't changed the docker-compose either (btw with :latest) 

Maybe just cache that needed to be refreshed? Not really sure why it happened twice. 

Sorry for the inconvenience and thank you.

**Comment by RaunoT** [comment]
Glad you got it sorted!
