### ISSUE TITLE
Simplified stats sharing

### ISSUE THREAD

**Issue by Cousclou** [RaunoT/plex-rewind#246]
### Description

I know that public sharing has been possible since ticket #209, but I find that it's not necessarily intuitive for users.

### Desired behavior

I would like to have a share button that copies the link so users can easily share their stats.

**Comment by RaunoT** [comment]
Public sharing has always been possible via reverse proxy - there is nothing more Plex Rewind can do from it's end to make this simpler.

What #209 did was add the ability for non-authenticated users to also be able to access the stats displayed by the app.

I'm personally not interested in adding a share button, considering you can just copy the URL or the already existant share buttons from inside browsers. Sorry!
