### ISSUE TITLE
Better Tutorial

### ISSUE THREAD

**Issue by stFfnbrnd** [RaunoT/plex-rewind#247]
### Description

Hi im a total linux noob and dont know mutch about docker.
a great addition would be a better tutorial.
Im a Unraid user and i dont really know what i have to do with:
Authentication Secret and Authentication URL

i really hope someone can help me

Greetings
Steffen

### Desired behavior

an easy to follow tutorial.

**Comment by RaunoT** [comment]
Hello,

Unfortunately the barrier to entry for this app is at least knowing the basics of Docker or Unraid. If those concepts are unfamiliar to you, I recommend you start from YouTube and other similar resources.
If you're an Unraid user, you can use the community app - see [README](https://github.com/RaunoT/plex-rewind?tab=readme-ov-file#unraid). The meaning of the auth secret and url is also described in the same file.

Good luck!
