### ISSUE TITLE
Error if user has no streams in library

### ISSUE THREAD

**Issue by jon4hz** [RaunoT/plex-rewind#248]
### Plex Rewind Version

v4.3.0

### Description

If a user has no streams in a library that is enabled for the rewind, there is an error.
In my case it was an audio library but it seems like the library type doesn't matter.

### Steps to reproduce

1. Have no streams in library
2. Watch rewind

### Screenshots

![2024-09-27_00-13](https://github.com/user-attachments/assets/9a5764bb-f574-4d20-b9c4-ce17f65067ed)

### Logs

```shell
[REWIND] -  TypeError: s.audio.top[0] is undefined
```

### Platform

desktop

### Device

Doesnt matter

### Operating System

Doesnt matter

### Browser and version

Doesnt matter

### Additional context

Happens on all platforms and devices.

**Comment by RaunoT** [comment]
Apologies for the spam, there was a bug in the release pipeline, it's now fixed :D

**Comment by jon4hz** [comment]
> Apologies for the spam, there was a bug in the release pipeline, it's now fixed :D

No worries. Thanks a lot for the quick fix! ^^
