### ISSUE TITLE
"This application needs to be configured by an administrator." even though settings.json is correct

### ISSUE THREAD

**Issue by Shaddowrunner414** [RaunoT/plex-rewind#264]
### Plex Rewind Version

4.3.2

### Description

First, I deployed plex-rewind via docker, using a docker volume instead of a bind mount. But I gradually changed everything to the point where I just copied the provided docker-compose.yml, edited the env-variables and ran the container. But with all these constellations, I get to the screen, where I have to enter the Tautulli URL and API-Key and the Plex URL.
After I enter them, I have to sign up with plex (which I do, using my server-owner-account). Plex says, the authentication is successfull and closes the window, but plex-rewind only redirects me to the screen that says 

> Setup required
> This application needs to be configured by an administrator.
> Login with Plex

I can do this however often I want with the same result. 
The logs folder in the container contains nothing, but the docker log throws `plex-rewind  | [TAUTULLI] - No user ID found!` 5 times every time I reload the plex-rewind page. 
I confirmed that Tautulli has access to my plex server and can see all active users (Refreshing them also works)

I found a reddit comment with the same issue, but the workaround there (editing the settings.json) [shouldn't be necessary anymore](https://www.reddit.com/r/Tautulli/comments/1eaxiev/comment/liuea8m/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) and does not help either.

I got the Tautulli API Key from `Settings > Web Interface > API > API-Key` and confirmed that the API is enabled

### Steps to reproduce

1. paste the provided docker-compose.yml to a local file
2. deploy the container with docker-compose up
3. enter required URLs and API-Key
4. Try to log in with Plex

### Platform

desktop

### Device

Desktop PC

### Operating System

Ubuntu 24.04.1 LTS

### Browser and version

Firefox 131.0 and Chrome 129.0.6668.90

**Comment by RaunoT** [comment]
What's the result when you go to `/api/missing-setting`?
For context, this error `[TAUTULLI] - No user ID found!` is just thrown, when a logged in user can't be found, which is expected in your case I guess.

**Comment by Shaddowrunner414** [comment]
when I append `/api/missing-setting` to `docker-ip:8383` I see a blank page with the text `"general.complete"`

**Comment by RaunoT** [comment]
Can you try manually editing all the complete keys to be true in `settings.json` and see if that resolves it?

**Comment by Shaddowrunner414** [comment]
I did that and now after the <sign in with plex> authentication, I can use the app, so that seems to be the solution.

Thank you very much for your help!
