### ISSUE TITLE
Invalid API key

### ISSUE THREAD

**Issue by Sietsevdm** [RaunoT/plex-rewind#280]
Im getting an Invalid API key error but the API key is copied directly from Tautulli.

**Comment by sdr19** [comment]
Having the same issue, tried regenerating the key with the same error.

**Comment by RaunoT** [comment]
Please use the provided issue templates next time.
How are you formatting the Tautulli URL? Are you adding the protocol (http/https) and using an IP address/domain name (192.168... or example.com)?

**Comment by sdr19** [comment]
My Tautulli URL is http://10.0.19.10:33400 and is accessible by web browser.

**Comment by kvalle22** [comment]
Having the same problem `Tautulli - invalid API key!`

![image](https://github.com/user-attachments/assets/3a0e889b-11fa-4b09-835c-179a2a8d35d8)

**Comment by RaunoT** [comment]
> Having the same problem `Tautulli - invalid API key!`
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/3a0e889b-11fa-4b09-835c-179a2a8d35d8)
> 
> 
> 
> 

Did you try removing the trailing slash?

**Comment by kvalle22** [comment]
OH MAN THAT FIXED IT, tysm!
![lil-yachty-drake](https://github.com/user-attachments/assets/3ec6d41c-d191-44d1-a1ce-319367c1cced)

**Comment by sdr19** [comment]
Still getting "invalid" without the trailing slash
![image](https://github.com/user-attachments/assets/3e1fcf2b-a066-42b7-90a6-7d4bc643db4f)

**Comment by RaunoT** [comment]
@sdr19 Can you try going to `<your-tautulli-url>/api/v2?apikey=<your-api-key>&cmd=status` and seeing if  `success ` is returned? If that's the case, your Docker configuration might be blocking Plex Rewind from accessing outside containers, as that's exactly the same request Plex Rewind makes.

**Comment by RaunoT** [comment]
@Sietsevdm can you please confirm if any of the above solutions work for you?

**Comment by Sietsevdm** [comment]
@RaunoT that seems to work but i can't log in to Plex and get redirected without any pop-up.

![image](https://github.com/user-attachments/assets/a99ed3f0-5f7f-4e15-9f70-2e5470f9b9ee)

**Comment by RaunoT** [comment]
I will close this out then.
For the login issue please have a look at #108 and #143.
