### ISSUE TITLE
Stuck on spinning wheel

### ISSUE THREAD

**Issue by dpeet** [RaunoT/plex-rewind#31]
Follow up from -> https://www.reddit.com/r/PleX/comments/18pd48j/plex_rewind_a_new_webbased_app_for_displaying/?share_id=TFGuooSL1u5l25IWC9VMD&utm_content=1&utm_medium=ios_app&utm_name=ioscss&utm_source=share&utm_term=1 

I got the error below initially
```
 => ERROR [plex-rewind deps 4/4] RUN   if [ -f yarn.lock ]; then yarn --frozen-lockfile;   elif [ -f package-lock.json ]; then npm ci;   elif [ -f pn  1.6s
------                                                                                                                                                      
 > [plex-rewind deps 4/4] RUN   if [ -f yarn.lock ]; then yarn --frozen-lockfile;   elif [ -f package-lock.json ]; then npm ci;   elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile;   else echo "Lockfile not found." && exit 1;   fi:                                                 
0.537 yarn global v1.22.19                                                                                                                                  
0.561 [1/4] Resolving packages...                                                                                                                           
0.828 [2/4] Fetching packages...                                                                                                                            
1.106 [3/4] Linking dependencies...
1.235 [4/4] Building fresh packages...
1.238 success Installed "pnpm@8.12.1" with binaries:
1.238       - pnpm
1.238       - pnpx
1.238 Done in 0.70s.
1.598  ERR_PNPM_FROZEN_LOCKFILE_WITH_OUTDATED_LOCKFILE  Cannot perform a frozen installation because the version of the lockfile is incompatible with this version of pnpm
1.598 
1.598 Try either:
1.598 1. Aligning the version of pnpm that generated the lockfile with the version that installs from it, or
1.598 2. Migrating the lockfile so that it is compatible with the newer version of pnpm, or
1.598 3. Using "pnpm install --no-frozen-lockfile".
1.598 Note that in CI environments, this setting is enabled by default.
------
failed to solve: process "/bin/sh -c if [ -f yarn.lock ]; then yarn --frozen-lockfile;   elif [ -f package-lock.json ]; then npm ci;   elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile;   else echo \"Lockfile not found.\" && exit 1;   fi" did not complete successfully: exit code: 1
```

I ran
```
pnpm install --no-frozen-lockfile
```
then 
``` 
docker compose build
```
and 
```
docker compose up
```

The application spins but has no error on the terminal or browser console

Running on Ubuntu 22.04, please let me know how I can help debug!

**Comment by dpeet** [comment]
Just to confirm, I pulled https://github.com/RaunoT/plex-rewind/commit/1004af0fd340705e37bfad1f64a45b68ac3cee82 and rebuilt with the same error as above

**Comment by RaunoT** [comment]
@dpeet Should be fixed in the latest, let me know if you still run into it!

**Comment by dpeet** [comment]
@RaunoT Good news! Got past the spinny wheel.  Bad news, still stuck.  I get to the screen that asks me to login.  When I click login, it thinks for a second than gives me the below "unable to complete this request"

![CleanShot 2023-12-24 at 01 29 28@2x](https://github.com/RaunoT/plex-rewind/assets/4729779/ae2d4fa2-6eef-438d-84e4-fdef51c9c29d)

Here's a snippet of the log where it's failing
![CleanShot 2023-12-24 at 01 33 11@2x](https://github.com/RaunoT/plex-rewind/assets/4729779/8daf8a28-1a0b-446c-b13e-e23bf95dc261)

**Comment by dpeet** [comment]
Actually I take that back!  Easy fix, I just needed to update the NEXT_PUBLIC_SITE_URL and NEXTAUTH_URL variables.   Probably would be good to add those to the documentation page.

**Comment by Jobinrandhawa** [comment]
> Actually I take that back! Easy fix, I just needed to update the NEXT_PUBLIC_SITE_URL and NEXTAUTH_URL variables. Probably would be good to add those to the documentation page.

Can you elaborate on what you did? What did you change the variables to?

**Comment by RaunoT** [comment]
> > Actually I take that back! Easy fix, I just needed to update the NEXT_PUBLIC_SITE_URL and NEXTAUTH_URL variables. Probably would be good to add those to the documentation page.
> 
> 
> 
> Can you elaborate on what you did? What did you change the variables to?

They should be set to the URL your page is running on.

**Comment by Jobinrandhawa** [comment]
> > > Actually I take that back! Easy fix, I just needed to update the NEXT_PUBLIC_SITE_URL and NEXTAUTH_URL variables. Probably would be good to add those to the documentation page.
> > 
> > 
> > Can you elaborate on what you did? What did you change the variables to?
> 
> They should be set to the URL your page is running on.

So if i am running on Vercel I should put them as the domain I have been assigned?

**Comment by dpeet** [comment]
Exactly what @RaunoT said, I'm running a reverse proxy with caddy and set the variable to the url of my reverse proxy.
