### ISSUE TITLE
Publish as an Unraid Community App

### ISSUE THREAD

**Issue by RaunoT** [RaunoT/plex-rewind#33]
Looks like there's quite a bit of community interest in this:
https://www.reddit.com/r/PleX/comments/18pd48j/comment/kenv74z/?utm_source=share&utm_medium=web2x&context=3

**Comment by nwithan8** [comment]
I explored this a few months ago, but without a pre-built Docker container is was a no-go. I saw the difficulty around that in #32 , but added a reminder to myself to check back in on this project just in case it ever came about. The odds that the first commit to the project in six months is the release of a pre-built Docker container, and it just so happened to be only 5 hours ago must be a sign from the universe.

Anyway, I'm working on this right now.

**Comment by RaunoT** [comment]
That's great @nwithan8! Re-opening for visibilty.

**Comment by mayberts** [comment]
I'm trying to run this using the unraid template and I get the following error when trying to auth with plex "We were unable to complete this request.
You will be redirected automatically." then it redirects to the Plex app

**Comment by mayberts** [comment]
> I'm trying to run this using the unraid template and I get the following error when trying to auth with plex "We were unable to complete this request. You will be redirected automatically." then it redirects to the Plex app

my bad, changed the URL from localhost to the IP :)

**Comment by nwithan8** [comment]
Plex Rewind is now available on Unraid: https://unraid.net/community/apps?q=plex-rewind#r

Recommend closing as completed.

**Comment by RaunoT** [comment]
Thanks @nwithan8!

**Comment by RaunoT** [comment]
@nwithan8 re: documentation, please feel free to make a PR. I think this would be very beneficial, considering the interest in running on Unraid.

**Comment by nwithan8** [comment]
> @nwithan8 re: documentation, please feel free to make a PR. I think this would be very beneficial, considering the interest in running on Unraid.

Opened #190

**Comment by suvikp** [comment]
Possible to add a Loading gif / animation while it takes a while to generate the rewind info?
