### ISSUE TITLE
Images not loading

### ISSUE THREAD

**Issue by dpeet** [RaunoT/plex-rewind#35]
![CleanShot 2023-12-24 at 01 43 20@2x](https://github.com/RaunoT/plex-rewind/assets/4729779/45ac56bc-2463-478f-99d5-15858c2696a4)

After logging in, all of the images are failing with the response `"url" parameter is not allowed`

**Comment by RaunoT** [comment]
@dpeet, I actually pushed a fix for this and updated the README regarding this a few minutes ago.
Please check that the domains where the pictures are loading from, are included in `next.config.js`

**Comment by dpeet** [comment]
aha, nice!  Easy fix there.
