### ISSUE TITLE
Forked to Vercel Error

### ISSUE THREAD

**Issue by Jobinrandhawa** [RaunoT/plex-rewind#36]
I forked the project and got it up and running to the login with plex page but plex returns "We were unable to complete this request.
You will be redirected automatically." and the goes to plex.tv.

**Comment by PizzaPino** [comment]
same problem for me.

**Comment by tarunkumar519** [comment]
After deploying to vercel you will be assgned a subdomain with vercel for your app. Have you updated this URL for ‎NEXT_PUBLIC_SITE_URL and ‎NEXTAUTH_URL inside environment variables in vercel? I think you may also have to change it inside next.config.js under images.remotePatterns.

**Comment by Jobinrandhawa** [comment]
> After deploying to vercel you will be assgned a subdomain with vercel for your app. Have you updated this URL for ‎NEXT_PUBLIC_SITE_URL and ‎NEXTAUTH_URL inside environment variables in vercel? I think you may also have to update this URL inside next.config.js under images.remotePatterns.

Yes this worked for me, thank you.

**Comment by tarunx** [comment]
Hey, however after updating this way now it says API auth error after login. Are you having same issue?

**Comment by Jobinrandhawa** [comment]
> Hey, however after updating this way now it says API auth error after login. Are you having same issue?

no, can you post a screenshot?

**Comment by tarunx** [comment]
It just goes to this page, i think you can check by just putting this after your url

something.vercel.app/api/auth/error

here something is my app name inside vercel
