### ISSUE TITLE
Covers only showing placeholders

### ISSUE THREAD

**Issue by TobiasDax** [RaunoT/plex-rewind#50]
### Description

When i launch plex-rewind all i see is placeholder images instead of real covers. No idea what i am missing.

Also file size for plex is only shown for Movies and 0 Bytes for everything else, but i guess thats unrelated :)

### Steps to reproduce

1. clone repo
2. set .env variables
3. build compose
4. run docker
5. open web interface

### Screenshots

<img width="1920" alt="image" src="https://github.com/RaunoT/plex-rewind/assets/42605856/739ba1f8-ce6c-4cb4-9cef-e71b19fd7431">

### Platform

desktop

### Device

Desktop

### Operating System

Docker throug ubuntu WLS2 on windows 11

### Browser and version

Chrome 120.0.6099.130

**Comment by RaunoT** [comment]
Can you please open the console and see if there are any errors there? Right click -> Inspect -> Console tab

Regarding the library size. The size is fetched from Tautulli. Make sure you have "Calculate Total File Sizes" enabled under "Settings -> General" in Tautulli. Note that if you didn't have it enabled, it might take quite a while to populate. If you have it enabled already and it's still not showing, you can refresh the library info in Tautulli by going to "Libraries -> {your library name} -> Media info -> Refresh media info".

Worth mentioning also that afaik, Tautulli doesn't update this periodically itself, which is kind of a bummer. Also, the refreshing process can be a bit buggy sometimes, but it seems to work itself out after a bit of time and a couple of restarts every now and then. YMMV.

Eitherway, we shouldn't display a value of 0, so reported under #51.

**Comment by RaunoT** [comment]
@TobiasDax Please verify that the value you use for `NEXT_PUBLIC_TAUTULLI_URL` is properly set in `next.config.js` under `images.remotePatterns` if you're using a custom value and rebuild your image.
It should follow the format of already existing values, e.g:

```
images: {
  remotePatterns: [
    {
      protocol: 'http',
      hostname: 'localhost',
    },
    {
      protocol: 'https',
      hostname: 'plex.tv',
    },
    {
      protocol: 'https',
      hostname: 'your-tautulli-host.com',
    }
  ],
},
```
